### ISSUE TITLE
Account Management

### ISSUE THREAD

**Issue by Assault** [khertan/ForRunners#34] opened 2017-03-15 18:26 UTC
Would it be possible to built sth. like an account management, so you can switch between different accounts?
I would like to use this app not only for Running. In my eyes its also the Perfect app for riding a bike or inline skates. And it would be great if the user could define different acounts so you can differnce between bike and running oder even between two persons, that use the same device .

**Comment by ahstro** [comment] 2017-03-16 07:02
Sort of a duplicate of #31 and, maybe, #19. :)

**Comment by jedie** [comment] 2017-04-08 12:44
yes the same as my #31 ;)

**Comment by brvier** [comment] 2018-04-17 15:32
There are now different session type in 1.2.1.

**Closed as completed by brvier** 2018-04-17 15:32 UTC
